package:
  name: taxbrain
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>=2.5.0"
    - "behresp>=0.9.0"
    - dask

  run:
    - python
    - "taxcalc>=2.4.2"
    - "behresp>=0.9.0"
    - dask
    - bokeh
    - markdown
    - cairo
    - pango
    - phantomjs
    - weasyprint
    - tabulate
    - selenium
    - pypandoc

about:
  home: https://github.com/PSLmodels/Tax-Brain
